---
# tasks file for workshop

- name: Install Apache webserver
  yum:
    name: "{{ apache_package }}"
    state: installed

- name: Request certificate for localhost
  command: |
    openssl req -newkey rsa:2048 -nodes -keyout /etc/pki/tls/private/localhost.key
    -x509 -days 365 -out /etc/pki/tls/certs/localhost.crt -subj '/CN=localhost'
  args:
    creates: /etc/pki/tls/certs/localhost.crt

- name: Start and enable Apache (systemd)
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
  ignore_errors: true
  register: service_result

- name: Start and enable Apache (command)
  command: /usr/sbin/httpd -k start
  args:
    creates: /run/httpd/httpd.pid
  when: service_result.failed
