---
# tasks file for workshop

- name: Install Apache webserver
  yum:
    name: "{{ apache_package }}"
    state: installed

- name: Start and enable Apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
